-- ADAMS PostgreSQL + Spring Boot Setup
-- Uses the UPDATED SQL attachment as the base, with compatibility columns required by the existing ADAMS JSP/Servlet code.
-- Target database: doc_admission_db
-- Windows usage:
--   createdb -U postgres doc_admission_db
--   psql -U postgres -d doc_admission_db -f src/main/resources/db/ADAMS_PostgreSQL_SpringBoot_Setup.sql

DROP TABLE IF EXISTS password_reset_tokens CASCADE;
DROP TABLE IF EXISTS print_logs CASCADE;
DROP TABLE IF EXISTS activity_log CASCADE;
DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS category_requirements CASCADE;
DROP TABLE IF EXISTS student_requirements CASCADE;
DROP TABLE IF EXISTS archived_students CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS requirement_types CASCADE;
DROP TABLE IF EXISTS student_categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP FUNCTION IF EXISTS trg_touch_updated_at() CASCADE;
DROP FUNCTION IF EXISTS trg_sync_file_data() CASCADE;

CREATE TABLE users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(100) UNIQUE,
  full_name VARCHAR(150),
  phone VARCHAR(30),
  role VARCHAR(20) NOT NULL DEFAULT 'staff',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login TIMESTAMP NULL,
  CONSTRAINT chk_users_role CHECK (role IN ('superadmin', 'admin', 'staff', 'student'))
);

CREATE TABLE student_categories (
  category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE requirement_types (
  requirement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requirement_name VARCHAR(150) NOT NULL UNIQUE,
  description TEXT,
  is_required BOOLEAN NOT NULL DEFAULT TRUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE category_requirements (
  category_requirement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id INTEGER NOT NULL,
  requirement_id INTEGER NOT NULL,
  is_required BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cr_category FOREIGN KEY (category_id) REFERENCES student_categories(category_id) ON DELETE CASCADE,
  CONSTRAINT fk_cr_requirement FOREIGN KEY (requirement_id) REFERENCES requirement_types(requirement_id) ON DELETE CASCADE,
  CONSTRAINT uq_category_requirement UNIQUE (category_id, requirement_id)
);

CREATE TABLE students (
  student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NULL,
  student_number VARCHAR(50) UNIQUE,
  student_name VARCHAR(255),
  last_name VARCHAR(100) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  middle_name VARCHAR(100),
  extension_name VARCHAR(20),
  email VARCHAR(100),
  phone VARCHAR(30),
  birth_date DATE,
  category_id INTEGER,
  remarks TEXT,
  admission_status VARCHAR(30) NOT NULL DEFAULT 'pending',
  is_archived BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL,
  CONSTRAINT fk_students_category FOREIGN KEY (category_id) REFERENCES student_categories(category_id) ON DELETE SET NULL,
  CONSTRAINT chk_students_admission_status CHECK (admission_status IN ('pending', 'incomplete', 'for_verification', 'approved', 'rejected', 'archived'))
);

CREATE TABLE archived_students (
  archive_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL,
  student_name VARCHAR(255),
  last_name VARCHAR(100),
  first_name VARCHAR(100),
  middle_name VARCHAR(100),
  email VARCHAR(100),
  phone VARCHAR(30),
  birth_date DATE,
  category_id INTEGER,
  remarks TEXT,
  archived_by INTEGER,
  archive_reason TEXT,
  archived_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  restored_at TIMESTAMP NULL,
  CONSTRAINT fk_archive_category FOREIGN KEY (category_id) REFERENCES student_categories(category_id) ON DELETE SET NULL,
  CONSTRAINT fk_archive_user FOREIGN KEY (archived_by) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE TABLE student_requirements (
  student_requirement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL,
  requirement_id INTEGER NOT NULL,
  file_name VARCHAR(255),
  file_path VARCHAR(500),
  file_content BYTEA,
  file_data BYTEA,
  mime_type VARCHAR(120),
  file_size BIGINT DEFAULT 0,
  uploaded_by INTEGER,
  status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  upload_date DATE,
  uploaded_at TIMESTAMP NULL,
  remarks TEXT,
  verified_by INTEGER,
  verified_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sr_student FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE,
  CONSTRAINT fk_sr_requirement FOREIGN KEY (requirement_id) REFERENCES requirement_types(requirement_id) ON DELETE CASCADE,
  CONSTRAINT fk_sr_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(user_id) ON DELETE SET NULL,
  CONSTRAINT fk_sr_verified_by FOREIGN KEY (verified_by) REFERENCES users(user_id) ON DELETE SET NULL,
  CONSTRAINT uq_student_requirement UNIQUE (student_id, requirement_id)
);

CREATE TABLE documents (
  document_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_requirement_id INTEGER NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  mime_type VARCHAR(120),
  file_size BIGINT DEFAULT 0,
  uploaded_by INTEGER,
  uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_documents_student_requirement FOREIGN KEY (student_requirement_id) REFERENCES student_requirements(student_requirement_id) ON DELETE CASCADE,
  CONSTRAINT fk_documents_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE TABLE activity_log (
  log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER,
  username VARCHAR(50),
  action VARCHAR(100) NOT NULL,
  module VARCHAR(100) NOT NULL,
  description TEXT,
  ip_address VARCHAR(45),
  log_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE TABLE print_logs (
  print_log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref_no VARCHAR(50) NOT NULL UNIQUE,
  student_id INTEGER NULL,
  document_type VARCHAR(100) NOT NULL,
  printed_by INTEGER,
  printed_by_name VARCHAR(150),
  printed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  campus_code VARCHAR(20) NOT NULL DEFAULT 'MN0',
  CONSTRAINT fk_print_student FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE SET NULL,
  CONSTRAINT fk_print_user FOREIGN KEY (printed_by) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE TABLE password_reset_tokens (
  token_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE,
  token VARCHAR(255) NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  used BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_prt_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION trg_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION trg_sync_file_data()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.file_content IS NOT NULL THEN
    NEW.file_data = NEW.file_content;
  ELSIF NEW.file_data IS NOT NULL THEN
    NEW.file_content = NEW.file_data;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER students_touch_updated_at
BEFORE UPDATE ON students
FOR EACH ROW EXECUTE FUNCTION trg_touch_updated_at();

CREATE TRIGGER student_requirements_touch_updated_at
BEFORE UPDATE ON student_requirements
FOR EACH ROW EXECUTE FUNCTION trg_touch_updated_at();

CREATE TRIGGER student_requirements_sync_file_data
BEFORE INSERT OR UPDATE ON student_requirements
FOR EACH ROW EXECUTE FUNCTION trg_sync_file_data();

CREATE INDEX idx_students_user_id ON students(user_id);
CREATE INDEX idx_students_category_id ON students(category_id);
CREATE INDEX idx_students_admission_status ON students(admission_status);
CREATE INDEX idx_student_requirements_student_id ON student_requirements(student_id);
CREATE INDEX idx_student_requirements_requirement_id ON student_requirements(requirement_id);
CREATE INDEX idx_documents_student_requirement_id ON documents(student_requirement_id);
CREATE INDEX idx_activity_log_user_id ON activity_log(user_id);
CREATE INDEX idx_activity_log_log_time ON activity_log(log_time);
CREATE INDEX idx_print_logs_ref_no ON print_logs(ref_no);

-- Seed users. Passwords are SHA-256 hashes.
-- admin / admin123
-- staff / staff123
INSERT INTO users (username, password, email, full_name, phone, role, is_active) VALUES
('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'admin@adams.local', 'System Administrator', '09170000000', 'superadmin', TRUE),
('staff', '10176e7b7b24d317acfcf8d2064cfd2f24e154f7b5a96603077d5ef813d6a6b6', 'staff@adams.local', 'Admission Staff', '09170000001', 'staff', TRUE);

INSERT INTO student_categories (category_name, description, sort_order, is_active) VALUES
('Freshman', 'First-time college applicant submitting entry-level admission requirements.', 1, TRUE),
('Transferee', 'Applicant transferring from another college or university.', 2, TRUE),
('Graduate Student', 'Applicant applying for a graduate-level program.', 3, TRUE),
('Returning Student', 'Former student applying for re-admission or continuation.', 4, TRUE);

INSERT INTO requirement_types (requirement_name, description, is_required, is_active) VALUES
('Birth Certificate', 'Official PSA or NSO birth certificate.', TRUE, TRUE),
('Form 138 / Report Card', 'Latest report card or senior high school academic record.', TRUE, TRUE),
('Good Moral Certificate', 'Certificate of good moral character issued by the previous school.', TRUE, TRUE),
('2x2 ID Picture', 'Recent 2x2 identification photo.', TRUE, TRUE),
('Valid ID', 'Government-issued, school-issued, or other valid identification document.', TRUE, TRUE),
('Transcript of Records', 'Official transcript for transferee or graduate applicant.', TRUE, TRUE);

INSERT INTO category_requirements (category_id, requirement_id, is_required)
SELECT c.category_id, r.requirement_id, TRUE
FROM student_categories c
JOIN requirement_types r ON r.requirement_name IN ('Birth Certificate','Good Moral Certificate','2x2 ID Picture','Valid ID')
WHERE c.category_name IN ('Freshman','Transferee','Graduate Student','Returning Student');

INSERT INTO category_requirements (category_id, requirement_id, is_required)
SELECT c.category_id, r.requirement_id, TRUE
FROM student_categories c
JOIN requirement_types r ON r.requirement_name = 'Form 138 / Report Card'
WHERE c.category_name = 'Freshman';

INSERT INTO category_requirements (category_id, requirement_id, is_required)
SELECT c.category_id, r.requirement_id, TRUE
FROM student_categories c
JOIN requirement_types r ON r.requirement_name = 'Transcript of Records'
WHERE c.category_name IN ('Transferee','Graduate Student','Returning Student');

INSERT INTO students (student_number, student_name, last_name, first_name, middle_name, email, phone, birth_date, category_id, admission_status, remarks)
SELECT '2026-0001', 'Dela Cruz, Ana Santos', 'Dela Cruz', 'Ana', 'Santos', 'ana.delacruz@example.com', '09171234567', DATE '2007-03-15', category_id, 'for_verification', 'Sample freshman applicant.'
FROM student_categories WHERE category_name = 'Freshman';

INSERT INTO students (student_number, student_name, last_name, first_name, middle_name, email, phone, birth_date, category_id, admission_status, remarks)
SELECT '2026-0002', 'Santos, Mark Reyes', 'Santos', 'Mark', 'Reyes', 'mark.santos@example.com', '09179876543', DATE '2005-09-20', category_id, 'incomplete', 'Sample transferee applicant.'
FROM student_categories WHERE category_name = 'Transferee';

INSERT INTO students (student_number, student_name, last_name, first_name, middle_name, email, phone, birth_date, category_id, admission_status, remarks)
SELECT '2026-0003', 'Garcia, Liza', 'Garcia', 'Liza', NULL, 'liza.garcia@example.com', '09175551234', DATE '2000-11-08', category_id, 'pending', 'Sample graduate applicant.'
FROM student_categories WHERE category_name = 'Graduate Student';

-- Generate student requirement checklist based on category rules.
INSERT INTO student_requirements (student_id, requirement_id, status)
SELECT s.student_id, cr.requirement_id, 'Pending'
FROM students s
JOIN category_requirements cr ON cr.category_id = s.category_id;

-- Demo status updates from the updated SQL attachment, converted to PostgreSQL syntax.
UPDATE student_requirements sr
SET status = 'Approved', verified_by = 1, verified_at = CURRENT_TIMESTAMP, remarks = 'Verified and approved.'
FROM students s, requirement_types r
WHERE sr.student_id = s.student_id
  AND sr.requirement_id = r.requirement_id
  AND s.student_number = '2026-0001'
  AND r.requirement_name IN ('Birth Certificate','Form 138 / Report Card','Valid ID');

UPDATE student_requirements sr
SET status = 'Rejected', verified_by = 1, verified_at = CURRENT_TIMESTAMP, remarks = 'Document image is unclear. Please resubmit.'
FROM students s, requirement_types r
WHERE sr.student_id = s.student_id
  AND sr.requirement_id = r.requirement_id
  AND s.student_number = '2026-0002'
  AND r.requirement_name = 'Valid ID';

-- Demo file/document metadata. The application stores uploaded file content in student_requirements.
UPDATE student_requirements sr
SET file_name = s.student_number || '_birth_certificate.pdf',
    file_path = '/uploads/' || s.student_number || '/birth_certificate.pdf',
    mime_type = 'application/pdf',
    file_size = 125000,
    uploaded_by = 2,
    status = 'Uploaded',
    uploaded_at = CURRENT_TIMESTAMP,
    upload_date = CURRENT_DATE,
    file_content = decode('255044462d312e340a', 'hex')
FROM students s, requirement_types r
WHERE sr.student_id = s.student_id
  AND sr.requirement_id = r.requirement_id
  AND s.student_number = '2026-0001'
  AND r.requirement_name = 'Birth Certificate';

INSERT INTO documents (student_requirement_id, file_name, file_path, mime_type, file_size, uploaded_by)
SELECT sr.student_requirement_id, sr.file_name, sr.file_path, sr.mime_type, sr.file_size, sr.uploaded_by
FROM student_requirements sr
JOIN students s ON s.student_id = sr.student_id
JOIN requirement_types r ON r.requirement_id = sr.requirement_id
WHERE s.student_number = '2026-0001' AND r.requirement_name = 'Birth Certificate';

INSERT INTO activity_log (user_id, username, action, module, description, ip_address, log_time) VALUES
(1, 'admin', 'LOGIN', 'Authentication', 'Administrator logged in successfully.', '127.0.0.1', CURRENT_TIMESTAMP),
(2, 'staff', 'UPLOAD', 'Documents', 'Staff uploaded a birth certificate for student 2026-0001.', '127.0.0.1', CURRENT_TIMESTAMP),
(1, 'admin', 'VERIFY', 'Requirements', 'Administrator approved submitted requirements for student 2026-0001.', '127.0.0.1', CURRENT_TIMESTAMP);

SELECT 'ADAMS PostgreSQL database setup completed successfully.' AS message;
