server.port=${PORT:8080}
server.address=0.0.0.0
server.servlet.context-path=/doc_ad_sys

spring.datasource.url=${ADAMS_DB_URL:jdbc:postgresql://localhost:5432/doc_admission_db}
spring.datasource.username=${ADAMS_DB_USER:postgres}
spring.datasource.password=${ADAMS_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

logging.level.org.springframework=INFO
